#!/usr/bin/env bash

# Credit to ThePrimeagen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=$(find ~/code -maxdepth 1 -mindepth 1 -type d)
    items+=$'\n/tmp'
    selected=$(echo "$items" | fzf)
fi

if [[ -z $selected ]]; then
    exit
fi

dirname=$(basename "$selected" | sed 's/\./_/g')

# Attempt to load the tmuxifier session
tmuxifier load-session "$dirname"
if [[ $? -eq 0 ]]; then
    exit 0
fi

# Fall back to the original tmux handling
tmux switch-client -t="$dirname"
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c "$selected" -d -s "$dirname" && tmux switch-client -t "$dirname" || tmux new -c "$selected" -A -s "$dirname"
